### ISSUE TITLE
Update to the new FortiGuard URL Scheme

### ISSUE THREAD

**Issue by Nabiljain** [SystemJargon/fortiguard-webfilter#2]
##Problem
Fortinet changed the URL scheme and the script no longer works

## Solution
The PS1 script can be updated with the following change
Change the Invoke-WebRequest command in line 80 to
$web = Invoke-WebRequest https://www.fortiguard.com/search?q=$url"&"engine=7
And the Category filter in Line 83 to
$stringup = $web.tostring() -split "[`r`n]" | select-string "The address has been found as"

**Comment by SystemJargon** [comment]
looking into this.

**Comment by SystemJargon** [comment]
@Nabiljain 

This issue should now be resolved by [this commit](https://github.com/SystemJargon/fortiguard-webfilter/commit/e45cdb25c63652688a18deea48347f7e1c530060).
